# Generated by Django 4.0.3 on 2023-06-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
